version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 2
    reviewers:
      - "daishiman"
    assignees:
      - "daishiman"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps(python)"
      include: "scope"
    # セキュリティアップデートの自動PR
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # 大きなバージョンアップデートは手動で確認
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # JavaScript/TypeScript dependencies (メインプロジェクト)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 2
    reviewers:
      - "daishiman"
    assignees:
      - "daishiman"
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "deps(js)"
      include: "scope"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # メジャーバージョンアップは手動管理
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # React/Next.jsはメジャー・マイナーを手動管理（パッチは自動）
      - dependency-name: "next"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 3
    reviewers:
      - "daishiman"
    assignees:
      - "daishiman"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "deps(docker)"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 3
    reviewers:
      - "daishiman"
    assignees:
      - "daishiman"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps(actions)"