# AutoForgeNexus pnpm Workspace Configuration
# DDD + Event-Driven Architecture with Clean Architecture Layers

packages:
  # Frontend packages (Next.js 15.5 + React 19)
  - 'packages/frontend'
  - 'packages/frontend/*'

  # Backend packages (Python integration via scripts)
  - 'packages/backend'
  - 'packages/backend/*'

  # Shared/Common packages
  - 'packages/shared'
  - 'packages/shared/*'

  # Domain packages (DDD structure)
  - 'packages/domain/*'

  # Infrastructure packages
  - 'packages/infrastructure/*'

  # Application layer packages
  - 'packages/application/*'

  # UI/Component packages
  - 'packages/ui/*'

  # Testing packages
  - 'packages/testing/*'

  # Utility packages
  - 'packages/utils/*'

  # Tool packages
  - 'packages/tools/*'

# Exclude specific directories
exclude:
  - '**/node_modules/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/.next/**'
  - '**/coverage/**'
  - '**/temp/**'
  - '**/tmp/**'