name: ✨ Feature Request
description: 新機能の提案・機能改善の要望
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        新機能の提案ありがとうございます。以下の情報を提供してください。

  - type: textarea
    id: problem
    attributes:
      label: 解決したい問題
      description: どのような問題や課題を解決したいですか？
      placeholder: |
        現在の問題点や不便な点を具体的に説明してください。
        例: プロンプトの履歴を検索する機能がないため、過去のプロンプトを見つけるのに時間がかかる
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 提案する解決策
      description: どのような機能や改善を提案しますか？
      placeholder: |
        具体的な機能や実装方法のアイデアを記載してください。
        例: プロンプト履歴に検索バーを追加し、キーワードやタグで検索できるようにする
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 他に検討した解決策があれば記載してください
      placeholder: |
        - フィルタリング機能の追加
        - カテゴリー別の表示
        - お気に入り機能の実装
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: この機能の重要度はどの程度ですか？
      options:
        - Must Have - 必須機能
        - Should Have - あるべき機能
        - Nice to Have - あると良い機能
        - Future - 将来的に検討
      default: 2
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: カテゴリー
      description: この機能はどの領域に関連しますか？
      options:
        - UI/UX
        - プロンプト管理
        - AI/LLM統合
        - 評価・分析
        - バージョン管理
        - コラボレーション
        - パフォーマンス
        - セキュリティ
        - その他
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: ユースケース
      description: この機能をどのように使用しますか？具体的な使用例を記載してください
      placeholder: |
        1. ユーザーがプロンプト履歴ページを開く
        2. 検索バーに「画像生成」と入力
        3. 過去の画像生成関連のプロンプトがフィルタリングされて表示
        4. 必要なプロンプトを選択して再利用
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: 期待される効果
      description: この機能によってどのような効果が期待できますか？
      placeholder: |
        - プロンプト検索時間を90%削減
        - プロンプトの再利用率が向上
        - チーム間でのナレッジ共有が促進
    validations:
      required: false

  - type: textarea
    id: mockup
    attributes:
      label: モックアップ・参考資料
      description: UIのスケッチ、参考となる他サービスの画像などがあれば添付してください
      placeholder: |
        画像やリンクをここに追加してください
    validations:
      required: false

  - type: textarea
    id: technical
    attributes:
      label: 技術的な考慮事項
      description: 実装に関する技術的な提案や懸念事項があれば記載してください
      placeholder: |
        - Elasticsearchを使用した全文検索
        - フロントエンドでのリアルタイムフィルタリング
        - インデックス作成のタイミング
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: チェックリスト
      description: 提出前に以下を確認してください
      options:
        - label: 既存のFeature Requestに同じ提案がないことを確認しました
          required: true
        - label: この機能がプロジェクトの目的に合致することを確認しました
          required: true
        - label: 実装の複雑さを考慮しました
          required: false